// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cikipfyxvpacpbmysvwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpa2lwZnl4dnBhY3BibXlzdndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzQ0MjUsImV4cCI6MjA2OTExMDQyNX0.McC6pdgOa89Fd0uWVrWTm6CROj3Iq1TiRgjMNSrlAps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});